# Copyright (c) Robert Bosch GmbH
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

name: Update Review Session Files for Pull Requests on base commit

on:
  push:

jobs:
  build:
    # The type of runner that the job will run on
    runs-on: [self-hosted, lemontree]
    timeout-minutes: 15
    steps:    
      - name: CreateComments
        if: ${{ steps.checkNumber.outputs.count > 0}}
        uses: actions/github-script@v5
        with:
          script: |
             await github.rest.issues.createComment({
                issue_number: pr.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                body: "This is a comment from the demoworkflow"
            
